repos:
  - repo: git@github.com:humitos/mirrors-autoflake.git
    rev: v1.1
    hooks:
      - id: autoflake
        args: ['--in-place', "--remove-all-unused-imports"]

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://gitlab.com/pycqa/flake8
    rev: master
    hooks:
      - id: flake8
        types: [python]
        args: ["--ignore=E203,W503,E501"]

  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.8
        types: [python]
